# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release
on:
  push:
    tags:        
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sql.translate
        path: target/*.jar
    - name: Save Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sql.translate
        path: target/*.jar
    - name: Get Git Tag Name
      run: echo GIT_TAG=${GITHUB_REF:10} >> $GITHUB_ENV
    - name: Set Image Tag
      run: echo IMAGE_TAG=${GIT_TAG#v} >> $GITHUB_ENV
    - name: Build and Push Image Tag
      run: bash ./.github/scripts/pushdocker.sh ${{secrets.DOCKER_USERNAME}} ${{secrets.DOCKER_PASSWORD}}
